# Generated by Django 5.0.6 on 2025-05-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.material'),
        ),
    ]
